from pathlib import Path
import html
from docx_exporter import export_docx

def compose_markdown(title, case_dir, source_names):
    parts=[f"# {title}","","> Generated by the SAF documentation pipeline from versioned Markdown sources.",""]
    for name in source_names:
        parts.extend([f"<!-- source: {name} -->","",(case_dir/name).read_text(encoding="utf-8").strip(),""])
    return "\n".join(parts).rstrip()+"\n"

def markdown_to_basic_html(markdown,title):
    return f'<!doctype html><html><head><meta charset="utf-8"><title>{html.escape(title)}</title></head><body><pre>{html.escape(markdown)}</pre></body></html>'

def export_all(build_dir,slug,title,markdown,outputs):
    build_dir.mkdir(parents=True,exist_ok=True); produced=[]
    if "markdown" in outputs:
        x=build_dir/f"{slug}.md"; x.write_text(markdown,encoding="utf-8"); produced.append(x)
    if "html" in outputs:
        x=build_dir/f"{slug}.html"; x.write_text(markdown_to_basic_html(markdown,title),encoding="utf-8"); produced.append(x)
    if "docx" in outputs: produced.append(export_docx(build_dir/f"{slug}.docx",markdown))
    return produced
