from pathlib import Path
import html


def compose_markdown(title: str, case_dir: Path, source_names: list[str]) -> str:
    parts = [
        f"# {title}",
        "",
        "> Generated by the SAF documentation pipeline from versioned Markdown sources.",
        "",
    ]

    for name in source_names:
        text = (case_dir / name).read_text(encoding="utf-8").strip()
        parts.extend([f"<!-- source: {name} -->", "", text, ""])

    return "\n".join(parts).rstrip() + "\n"


def markdown_to_basic_html(markdown: str, title: str) -> str:
    body = html.escape(markdown)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>
body {{ max-width: 980px; margin: 2rem auto; padding: 0 1rem; font-family: system-ui, sans-serif; }}
pre {{ white-space: pre-wrap; line-height: 1.45; }}
</style>
</head>
<body>
<pre>{body}</pre>
</body>
</html>
"""


def export_all(build_dir: Path, slug: str, title: str, markdown: str, outputs: list[str]) -> list[Path]:
    build_dir.mkdir(parents=True, exist_ok=True)
    produced = []

    if "markdown" in outputs:
        path = build_dir / f"{slug}.md"
        path.write_text(markdown, encoding="utf-8")
        produced.append(path)

    if "html" in outputs:
        path = build_dir / f"{slug}.html"
        path.write_text(markdown_to_basic_html(markdown, title), encoding="utf-8")
        produced.append(path)

    return produced
